############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "PUBLICATIONS"
url = "#publications"
weight = 2

[[main]]
name = "PROJECTS"
url = "#projects"
weight = 3

[[main]]
name = "OTHER WORKS"
url = "#others"
weight = 4








# footer menu
[[footer]]
name = "About"
url = "https://wangxu.ai/#biography"
weight = 1

[[footer]]
name = "GIX"
url = "https://gix.tsinghua.edu.cn/"
weight = 2

[[footer]]
name = "Template"
url = "https://hugoplate.netlify.app/"
weight = 3

